const commonStrings = <String, Map<String, String>>{
  'save': {
    'en': 'Save',
    'no': 'Lagre',
    'sv': 'Spara',
    'de': 'Speichern',
    'da': 'Gem',
  },
  'cancel': {
    'en': 'Cancel',
    'no': 'Avbryt',
    'sv': 'Avbryt',
    'de': 'Abbrechen',
    'da': 'Annuller',
  },
  'delete': {
    'en': 'Delete',
    'no': 'Slett',
    'sv': 'Radera',
    'de': 'Löschen',
    'da': 'Slet',
  },
  'dontSave': {
    'en': "Don't save",
    'no': 'Ikke lagre',
    'sv': 'Spara inte',
    'de': 'Nicht speichern',
    'da': 'Gem ikke',
  },
  'unsavedChanges': {
    'en': 'Unsaved changes',
    'no': 'Ulagrede endringer',
    'sv': 'Osparade ändringar',
    'de': 'Ungespeicherte Änderungen',
    'da': 'Ikke-gemte ændringer',
  },
  'unsavedChangesBody': {
    'en': 'You have unsaved changes. Do you want to save before leaving?',
    'no': 'Du har ulagrede endringer. Vil du lagre før du forlater?',
    'sv': 'Du har osparade ändringar. Vill du spara innan du lämnar?',
    'de': 'Sie haben ungespeicherte Änderungen. Möchten Sie vor dem Verlassen speichern?',
    'da': 'Du har ikke-gemte ændringer. Vil du gemme, før du forlader?',
  },
  'search': {
    'en': 'Search',
    'no': 'Søk',
    'sv': 'Sök',
    'de': 'Suchen',
    'da': 'Søg',
  },
  'loading': {
    'en': 'Loading...',
    'no': 'Laster...',
    'sv': 'Laddar...',
    'de': 'Laden...',
    'da': 'Indlæser...',
  },
  'error': {
    'en': 'Error',
    'no': 'Feil',
    'sv': 'Fel',
    'de': 'Fehler',
    'da': 'Fejl',
  },
  'unknownRoute': {
    'en': 'Unknown route',
    'no': 'Ukjent rute',
    'sv': 'Okänd rutt',
    'de': 'Unbekannte Route',
    'da': 'Ukendt rute',
  },
  'language': {
    'en': 'Language',
    'no': 'Språk',
    'sv': 'Språk',
    'de': 'Sprache',
    'da': 'Sprog',
  },
};
