const navStrings = <String, Map<String, String>>{
  'dashboard': {
    'en': 'Dashboard',
    'no': 'Dashbord',
    'sv': 'Dashboard',
    'de': 'Dashboard',
    'da': 'Dashboard',
  },
  'calendar': {
    'en': 'Calendar',
    'no': 'Kalender',
    'sv': 'Kalender',
    'de': 'Kalender',
    'da': 'Kalender',
  },
  'newOffer': {
    'en': 'New offer',
    'no': 'Nytt tilbud',
    'sv': 'Nytt erbjudande',
    'de': 'Neues Angebot',
    'da': 'Nyt tilbud',
  },
  'editOffers': {
    'en': 'Edit offers',
    'no': 'Rediger tilbud',
    'sv': 'Redigera erbjudanden',
    'de': 'Angebote bearbeiten',
    'da': 'Rediger tilbud',
  },
  'archive': {
    'en': 'Archive',
    'no': 'Arkiv',
    'sv': 'Arkiv',
    'de': 'Archiv',
    'da': 'Arkiv',
  },
  'customers': {
    'en': 'Customers',
    'no': 'Kunder',
    'sv': 'Kunder',
    'de': 'Kunden',
    'da': 'Kunder',
  },
  'invoices': {
    'en': 'Invoices',
    'no': 'Fakturaer',
    'sv': 'Fakturor',
    'de': 'Rechnungen',
    'da': 'Fakturaer',
  },
  'economy': {
    'en': 'Economy',
    'no': 'Økonomi',
    'sv': 'Ekonomi',
    'de': 'Finanzen',
    'da': 'Økonomi',
  },
  'issues': {
    'en': 'Issues',
    'no': 'Feilrapport',
    'sv': 'Felrapporter',
    'de': 'Fehlermeldungen',
    'da': 'Fejlrapporter',
  },
  'chat': {
    'en': 'Chat',
    'no': 'Chat',
    'sv': 'Chatt',
    'de': 'Chat',
    'da': 'Chat',
  },
  'contacts': {
    'en': 'Contacts',
    'no': 'Kontakter',
    'sv': 'Kontakter',
    'de': 'Kontakte',
    'da': 'Kontakter',
  },
  'busRequests': {
    'en': 'Bus Requests',
    'no': 'Bussforespørsler',
    'sv': 'Bussförfrågningar',
    'de': 'Busanfragen',
    'da': 'Busforespørgsler',
  },
  'settings': {
    'en': 'Settings',
    'no': 'Innstillinger',
    'sv': 'Inställningar',
    'de': 'Einstellungen',
    'da': 'Indstillinger',
  },
  'routeManager': {
    'en': 'Route Manager',
    'no': 'Ruteadministrasjon',
    'sv': 'Rutthantering',
    'de': 'Routenverwaltung',
    'da': 'Ruteadministration',
  },
};
